import { supabase, message } from "./app.js";
const form=document.getElementById("completeProfileForm");
const box=document.getElementById("profileMessage");
const submit=document.getElementById("completeProfileSubmit");
const next=new URLSearchParams(location.search).get("next") || "index.html";
function phone(v){const x=String(v||"").replace(/[^\d+]/g,""); if(x.startsWith("+62"))return "0"+x.slice(3); if(x.startsWith("62"))return "0"+x.slice(2); return x;}
function safeNext(v){try{const u=new URL(v,location.href);return u.origin===location.origin?`${u.pathname.split("/").pop()||"index.html"}${u.search}${u.hash}`:"index.html";}catch{return "index.html";}}
async function init(){const {data:{user}}=await supabase.auth.getUser(); if(!user){location.href="login.html";return;} const {data:p}=await supabase.from("profiles").select("username,full_name,phone,city,address,postal_code").eq("id",user.id).maybeSingle(); if(p){for(const k of ["username","full_name","phone","city","address","postal_code"]){if(form.elements[k]&&p[k])form.elements[k].value=p[k];} if(user.user_metadata?.full_name&&!form.elements.full_name.value)form.elements.full_name.value=user.user_metadata.full_name;}}
for(const n of ["phone","emergency_contact_phone"]){form.elements[n]?.addEventListener("input",e=>e.target.value=e.target.value.replace(/[^0-9+]/g,"").slice(0,20));}
for(const n of ["identity_last4","transaction_pin","confirm_transaction_pin"]){form.elements[n]?.addEventListener("input",e=>e.target.value=e.target.value.replace(/\D/g,"").slice(0,6));}
form.addEventListener("submit",async e=>{e.preventDefault(); if(!form.reportValidity())return; const v=Object.fromEntries(new FormData(form)); const pin=String(v.transaction_pin||""); if(!/^\d{6}$/.test(pin)||pin!==String(v.confirm_transaction_pin||"")){message(box,"PIN harus 6 digit dan konfirmasi harus sama.","error");return;} if(new Set(pin).size===1){message(box,"Jangan gunakan PIN dengan angka yang sama semua.","error");return;} const ph=phone(v.phone), eph=phone(v.emergency_contact_phone); if(!/^08\d{8,12}$/.test(ph.replace(/\D/g,""))){message(box,"Nomor WhatsApp tidak valid.","error");return;} if(!/^08\d{8,12}$/.test(eph.replace(/\D/g,""))){message(box,"Nomor kontak darurat tidak valid.","error");return;} submit.disabled=true;submit.textContent="Menyimpan...";try{const {data:{user}}=await supabase.auth.getUser(); if(!user)throw new Error("Sesi login tidak ditemukan."); const profile={username:String(v.username).trim(),full_name:String(v.full_name).trim(),phone:ph,city:String(v.city).trim(),address:String(v.address).trim(),postal_code:String(v.postal_code||"").trim()||null,identity_type:String(v.identity_type),identity_last4:String(v.identity_last4),emergency_contact_name:String(v.emergency_contact_name).trim(),emergency_contact_phone:eph}; const {error}=await supabase.rpc("complete_google_profile",{p_profile:profile,p_pin:pin}); if(error)throw error; message(box,"Profil dan PIN berhasil disimpan. Mengarahkan ke AOC...","success"); setTimeout(()=>location.href=safeNext(next),500);}catch(err){message(box,err.message||"Profil gagal disimpan.","error");}finally{submit.disabled=false;submit.textContent="Simpan & Masuk";}});
init();
